version: "3"
services:
  snake-game-multiplayer:
    container_name: snake-game-multiplayer
    image: "registry.gitlab.com/bittokazi/snake-game-2d-multiplayer/backend-and-web-client:latest"
    restart: unless-stopped
    env_file: ./.env
    network_mode: "bridge"
    ports:
      - "43001:3001"
