name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repositoty
        uses: actions/checkout@v3

      - name: Log into registry registry.gitlab.com
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: bittokazi
          password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}

      - name: Build and Push Game Image
        run: docker build . --file ./Dockerfile --tag registry.gitlab.com/bittokazi/snake-game-2d-multiplayer/backend-and-web-client:latest && docker push registry.gitlab.com/bittokazi/snake-game-2d-multiplayer/backend-and-web-client:latest
